# Generated by Django 3.2.8 on 2021-11-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Customers',
        ),
    ]
