# Generated by Django 3.2.8 on 2021-11-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20211111_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=19.99, max_digits=5),
        ),
    ]
