# Generated by Django 3.2.8 on 2021-11-13 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_payment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FutureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('future', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.customer')),
            ],
        ),
    ]
