# Generated by Django 3.2.8 on 2021-11-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20211113_1300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FutureRequest',
        ),
    ]
