# Generated by Django 3.2.8 on 2021-11-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_delete_futurerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='codeinstitute', max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='testtest', max_length=30),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=60, null=True),
        ),
    ]
